basic service setup
UWOrbital/UWOrbitalCDHAPI pull request #5
Opened 2022-03-07 03:23 UTC by KevinLe563

PR for settings up services. Adding/modifying services should be done by branching off of this branch.

2022-03-07 03:39 UTC, KevinLe563 commented
for adding/modifying future services should we branch off this child branch or just merge this one and then branch off main?

2022-03-31 03:41 UTC, dgobalak requested changes

2022-03-31 03:41 UTC, dgobalak commented on include/service/telemetry_collection_service.h
> +/**
Could you add an include guard for this too?

2022-03-31 03:41 UTC, dgobalak commented on include/service/system_status_service.h
> +/**
Could you add an include guard for this header file?

2022-03-31 03:41 UTC, dgobalak commented on include/service/system_status_service.h
> +int sys_reboot(void);
I'd use uint8_t as the return type for all of these functions.

2022-03-31 03:41 UTC, dgobalak commented on include/service/system_status_service.h
> +int sys_emergency_state();
Is there a reason why this function doesn't have a void argument, but the one above does?

2022-03-31 04:37 UTC, KevinLe563 commented on include/service/system_status_service.h
> +int sys_reboot(void);
Just followed the csp practice of just using int, not sure if uint8_t is preferred?

2022-03-31 05:02 UTC, dgobalak commented on include/service/system_status_service.h
> +int sys_reboot(void);
Interesting. Ya if csp uses int for their return types, I guess it's better to stay consistent (unless we wanted to rewrite csp lol).

2022-03-31 05:04 UTC, dgobalak commented on include/service/telemetry_collection_service.h
> +int struct_to_char_buff(void * inbuf, int inlen);
I'd make the inlen parameter type uint8_t. I think csp uses uint for their parameters when needed.

2022-03-31 05:06 UTC, dgobalak commented on include/service/telemetry_collection_service.h
> +int struct_to_char_buff(void * inbuf, int inlen);
Idk what the max value for inlen is tho, so maybe uint32_t or something would be better.

2022-03-31 05:06 UTC, dgobalak commented on include/service/telemetry_collection_service.h
> +int struct_to_char_buff(void * inbuf, int inlen);
And this applies to the outlen parameter in the char_buff_to_struct function too.

2022-03-31 05:14 UTC, dgobalak commented on include/service/telemetry_collection_service.h
> +  @return 0 if successful, else error code
In the future, we could make a return typedef for error codes.

2022-04-01 01:52 UTC, KevinLe563 commented on include/service/system_status_service.h
> +int sys_reboot(void);
We'll keep it as int for now, we can just change it later if necessary

2022-04-01 02:32 UTC, KevinLe563 commented on include/service/telemetry_collection_service.h
> +int struct_to_char_buff(void * inbuf, int inlen);
Yeah thats fair, csp uses int for their outbuf and inbuf lengths so I don't want to mix the types but i guess we could change csp to use uint8/32

2022-04-01 02:32 UTC, KevinLe563 commented on include/service/telemetry_collection_service.h
> +  @return 0 if successful, else error code
just going to add a TODO for now

2022-04-01 03:43 UTC, dgobalak commented on include/service/telemetry_collection_service.h
> +enum subsystem_port_t {
Is there a reason why there isn't a typedef for this?

2022-04-04 02:49 UTC, dgobalak approved these changes
Looks good to me.

2022-04-05 00:00 UTC, CyStorm approved these changes

2022-04-05 00:00 UTC, merged